sonar.organization=ti-tecnologico-de-monterrey-oficial

sonar.projectKey=ti-tecnologico-de-monterrey-oficial_issuer-coordinator
sonar.projectName=issuer-coordinator

sonar.sourceEncoding=UTF-8

# Codigo fuente
sonar.sources=src,server.js

# Pruebas
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js

sonar.exclusions=src/**/*.test.js,src/test-fixtures/**,coverage/**,logs/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Esperar resultado del Quality Gate
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

